//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1182.0 using the following command:
// xscgen -n DacPacDeployer.Schema .\deploy-report.xsd
namespace DacPacDeployer.Schema
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemType", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ItemTypeIssue> _issue;
        
        [System.Xml.Serialization.XmlElementAttribute("Issue")]
        public System.Collections.ObjectModel.Collection<ItemTypeIssue> Issue
        {
            get
            {
                return _issue;
            }
            private set
            {
                _issue = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Issue collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueSpecified
        {
            get
            {
                return (this.Issue.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ItemType" /> class.</para>
        /// </summary>
        public ItemType()
        {
            this._issue = new System.Collections.ObjectModel.Collection<ItemTypeIssue>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Value")]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Type")]
        public string Type { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemTypeIssue", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemTypeIssue
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public int Id { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IssueType", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IssueType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Value")]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public int Id { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeploymentReport", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DeploymentReport", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    public partial class DeploymentReport
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _errors;
        
        [System.Xml.Serialization.XmlArrayAttribute("Errors")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Error", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
        public System.Collections.ObjectModel.Collection<string> Errors
        {
            get
            {
                return _errors;
            }
            private set
            {
                _errors = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Errors collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorsSpecified
        {
            get
            {
                return (this.Errors.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DeploymentReport" /> class.</para>
        /// </summary>
        public DeploymentReport()
        {
            this._errors = new System.Collections.ObjectModel.Collection<string>();
            this._warnings = new System.Collections.ObjectModel.Collection<string>();
            this._alerts = new System.Collections.ObjectModel.Collection<DeploymentReportAlertsAlert>();
            this._operations = new System.Collections.ObjectModel.Collection<DeploymentReportOperationsOperation>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _warnings;
        
        [System.Xml.Serialization.XmlArrayAttribute("Warnings")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Warning", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
        public System.Collections.ObjectModel.Collection<string> Warnings
        {
            get
            {
                return _warnings;
            }
            private set
            {
                _warnings = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Warnings collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarningsSpecified
        {
            get
            {
                return (this.Warnings.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DeploymentReportAlertsAlert> _alerts;
        
        [System.Xml.Serialization.XmlArrayAttribute("Alerts")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Alert", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
        public System.Collections.ObjectModel.Collection<DeploymentReportAlertsAlert> Alerts
        {
            get
            {
                return _alerts;
            }
            private set
            {
                _alerts = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Alerts collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlertsSpecified
        {
            get
            {
                return (this.Alerts.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DeploymentReportOperationsOperation> _operations;
        
        [System.Xml.Serialization.XmlArrayAttribute("Operations")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Operation", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
        public System.Collections.ObjectModel.Collection<DeploymentReportOperationsOperation> Operations
        {
            get
            {
                return _operations;
            }
            private set
            {
                _operations = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Operations collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationsSpecified
        {
            get
            {
                return (this.Operations.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeploymentReportErrors", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeploymentReportErrors
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _error;
        
        [System.Xml.Serialization.XmlElementAttribute("Error")]
        public System.Collections.ObjectModel.Collection<string> Error
        {
            get
            {
                return _error;
            }
            private set
            {
                _error = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Error collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorSpecified
        {
            get
            {
                return (this.Error.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DeploymentReportErrors" /> class.</para>
        /// </summary>
        public DeploymentReportErrors()
        {
            this._error = new System.Collections.ObjectModel.Collection<string>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeploymentReportWarnings", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeploymentReportWarnings
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _warning;
        
        [System.Xml.Serialization.XmlElementAttribute("Warning")]
        public System.Collections.ObjectModel.Collection<string> Warning
        {
            get
            {
                return _warning;
            }
            private set
            {
                _warning = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Warning collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarningSpecified
        {
            get
            {
                return (this.Warning.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DeploymentReportWarnings" /> class.</para>
        /// </summary>
        public DeploymentReportWarnings()
        {
            this._warning = new System.Collections.ObjectModel.Collection<string>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeploymentReportAlerts", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeploymentReportAlerts
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DeploymentReportAlertsAlert> _alert;
        
        [System.Xml.Serialization.XmlElementAttribute("Alert")]
        public System.Collections.ObjectModel.Collection<DeploymentReportAlertsAlert> Alert
        {
            get
            {
                return _alert;
            }
            private set
            {
                _alert = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Alert collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlertSpecified
        {
            get
            {
                return (this.Alert.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DeploymentReportAlerts" /> class.</para>
        /// </summary>
        public DeploymentReportAlerts()
        {
            this._alert = new System.Collections.ObjectModel.Collection<DeploymentReportAlertsAlert>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeploymentReportAlertsAlert", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeploymentReportAlertsAlert
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<IssueType> _issue;
        
        [System.Xml.Serialization.XmlElementAttribute("Issue")]
        public System.Collections.ObjectModel.Collection<IssueType> Issue
        {
            get
            {
                return _issue;
            }
            private set
            {
                _issue = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Issue collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueSpecified
        {
            get
            {
                return (this.Issue.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DeploymentReportAlertsAlert" /> class.</para>
        /// </summary>
        public DeploymentReportAlertsAlert()
        {
            this._issue = new System.Collections.ObjectModel.Collection<IssueType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeploymentReportOperations", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeploymentReportOperations
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DeploymentReportOperationsOperation> _operation;
        
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public System.Collections.ObjectModel.Collection<DeploymentReportOperationsOperation> Operation
        {
            get
            {
                return _operation;
            }
            private set
            {
                _operation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Operation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationSpecified
        {
            get
            {
                return (this.Operation.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DeploymentReportOperations" /> class.</para>
        /// </summary>
        public DeploymentReportOperations()
        {
            this._operation = new System.Collections.ObjectModel.Collection<DeploymentReportOperationsOperation>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DeploymentReportOperationsOperation", Namespace="http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeploymentReportOperationsOperation
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ItemType> _item;
        
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public System.Collections.ObjectModel.Collection<ItemType> Item
        {
            get
            {
                return _item;
            }
            private set
            {
                _item = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Item collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemSpecified
        {
            get
            {
                return (this.Item.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DeploymentReportOperationsOperation" /> class.</para>
        /// </summary>
        public DeploymentReportOperationsOperation()
        {
            this._item = new System.Collections.ObjectModel.Collection<ItemType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
    }
}
